name: parity

on:
  workflow_dispatch:
    inputs:
      qmoms_ref:
        description: "vilkovgr/qmoms git ref (branch/tag/SHA)"
        required: false
        default: "main"
  schedule:
    - cron: "0 3 * * 1"  # optional: weekly run

permissions:
  contents: write

jobs:
  parity:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      # enable Python comparison in tests/vignette
      RQMOMS_BUILD_PY: "1"
      # which qmoms ref to install from GitHub
      QMOMS_REF: ${{ github.event.inputs.qmoms_ref || 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R (RSPM)
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies (incl. reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11 (toolcache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install numpy + qmoms into toolcache Python
        shell: bash
        run: |
          set -euxo pipefail
          python -V
          python -m pip install --upgrade pip
          python -m pip install numpy pandas scipy tqdm
          python -m pip install "git+https://github.com/vilkovgr/qmoms@${QMOMS_REF}"
          python - <<'PY'
          import sys, numpy, qmoms
          print("PY:", sys.executable)
          print("NumPy:", numpy.__version__)
          print("qmoms import: OK")
          PY

      # ===== R steps: bind reticulate to the SAME toolcache interpreter =====
      # We run clean R sessions (--vanilla) and neutralize user startup files.

      - name: Debug reticulate config (should see toolcache Python)
        env:
          RETICULATE_PYTHON: ${{ env.pythonLocation }}/bin/python
          R_ENVIRON_USER: /dev/null
          R_PROFILE_USER: /dev/null
        run: |
          Rscript --vanilla - <<'RS'
          stopifnot(requireNamespace("reticulate", quietly=TRUE))
          reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE)
          reticulate::py_discover_config()
          reticulate::py_run_string('import sys, numpy, qmoms; print("R sees:", sys.executable); print("NumPy:", numpy.__version__); print("qmoms: OK")')
          RS

      - name: Run tests (with Python parity)
        env:
          RETICULATE_PYTHON: ${{ env.pythonLocation }}/bin/python
          R_ENVIRON_USER: /dev/null
          R_PROFILE_USER: /dev/null
          RQMOMS_BUILD_PY: "1"
        run: |
          Rscript --vanilla -e 'reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE); devtools::test()'

      - name: Build vignettes + pkgdown (with comparison)
        env:
          RETICULATE_PYTHON: ${{ env.pythonLocation }}/bin/python
          R_ENVIRON_USER: /dev/null
          R_PROFILE_USER: /dev/null
          RQMOMS_BUILD_PY: "1"
        run: |
          Rscript --vanilla -e 'reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE); devtools::build_vignettes()'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
