name: parity

on:
  workflow_dispatch:
    inputs:
      qmoms_ref:
        description: "vilkovgr/qmoms git ref main"
        required: false
        default: "main"
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write

jobs:
  parity:
    runs-on: ubuntu-latest

    env:
      RQMOMS_BUILD_PY: "1"
      RQMOMS_VENV: ${{ github.workspace }}/python/.venv
      QMOMS_REF: ${{ github.event.inputs.qmoms_ref || 'main' }}

    steps:
      - name: Checkout rqmoms
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies (incl. reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create venv and install Python deps + vilkovgr/qmoms
        shell: bash
        run: |
          python -m venv python/.venv
          source python/.venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel build setuptools-scm
          python -m pip install numpy pandas scipy tqdm
          python -m pip install "git+https://github.com/vilkovgr/qmoms@${QMOMS_REF}"
          python -c "import sys,sysconfig,site; print('VENV:', sys.executable); import numpy; print('numpy:', numpy.__version__)"

      # (Optional) keep this, but step-level env is the real fix
      - name: Force reticulate to use the venv (best-effort)
        run: echo "RETICULATE_PYTHON=${{ github.workspace }}/python/.venv/bin/python" >> $GITHUB_ENV

      - name: Debug reticulate config
        env:
          RETICULATE_PYTHON: ${{ github.workspace }}/python/.venv/bin/python
        run: |
          Rscript -e 'print(Sys.getenv(c("RQMOMS_BUILD_PY","RQMOMS_VENV","RETICULATE_PYTHON"))); if (requireNamespace("reticulate", quietly=TRUE)) reticulate::py_discover_config()'

      - name: Run tests (with Python parity enabled)
        env:
          RETICULATE_PYTHON: ${{ github.workspace }}/python/.venv/bin/python
        run: Rscript -e 'devtools::test()'

      - name: Build vignettes and pkgdown (with comparison)
        env:
          RETICULATE_PYTHON: ${{ github.workspace }}/python/.venv/bin/python
        run: |
          Rscript -e 'devtools::build_vignettes()'
          Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
