name: parity

on:
  workflow_dispatch:
    inputs:
      qmoms_ref:
        description: "vilkovgr/qmoms git ref main"
        required: false
        default: "main"
  schedule:
    - cron: "0 3 * * 1"  # optional: Mondays 03:00 UTC

jobs:
  parity:
    runs-on: ubuntu-latest

    env:
      # Tell vignette/tests to run Python comparison
      RQMOMS_BUILD_PY: "1"
      # Path to the venv reticulate should use
      RQMOMS_VENV: ${{ github.workspace }}/python/.venv
      # Which ref of vilkovgr/qmoms to install (override via workflow_dispatch input)
      QMOMS_REF: ${{ github.event.inputs.qmoms_ref || 'main' }}

    steps:
      - name: Checkout rqmoms
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create venv and install Python deps + vilkovgr/qmoms from GitHub
        shell: bash
        run: |
          python -m venv python/.venv
          source python/.venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel build setuptools-scm
          python -m pip install numpy pandas scipy tqdm
          # Install qmoms directly from GitHub at the requested ref
          python -m pip install "git+https://github.com/vilkovgr/qmoms@${QMOMS_REF}"

      - name: Run tests (with Python parity enabled)
        run: Rscript -e 'devtools::test()'

      - name: Build vignettes and pkgdown (with comparison)
        run: |
          Rscript -e 'devtools::build_vignettes()'
          Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
