name: parity

on:
  workflow_dispatch:
    inputs:
      qmoms_ref:
        description: "vilkovgr/qmoms git ref (branch/tag/SHA)"
        required: false
        default: "main"
  schedule:
    - cron: "0 3 * * 1"  # optional weekly run

permissions:
  contents: write

jobs:
  parity:
    runs-on: ubuntu-latest

    env:
      # Vergleich aktivieren + venv-Pfad für Tests/Vignette
      RQMOMS_BUILD_PY: "1"
      RQMOMS_VENV: ${{ github.workspace }}/python/.venv
      QMOMS_REF: ${{ github.event.inputs.qmoms_ref || 'main' }}

    steps:
      - name: Checkout rqmoms
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies (incl. reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Create venv and install Python deps + vilkovgr/qmoms
        shell: bash
        run: |
          python -m venv python/.venv
          source python/.venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel build setuptools-scm
          python -m pip install numpy pandas scipy tqdm
          python -m pip install "git+https://github.com/vilkovgr/qmoms@${QMOMS_REF}"
          python - <<'PY'
          import sys
          print("VENV python:", sys.executable)
          import numpy; print("numpy:", numpy.__version__)
          import qmoms; print("qmoms import: OK")
          PY

      # --- WICHTIG: Kein RETICULATE_PYTHON setzen. In R-Skripten venv binden. ---

      - name: Debug reticulate config (bind venv inside R)
        run: |
          Rscript - <<'RS'
          Sys.unsetenv("RETICULATE_PYTHON")                  # evtl. geerbte Bindung löschen
          venv <- "python/.venv"                              # KEIN normalizePath()!
          if (requireNamespace("reticulate", quietly=TRUE)) {
            reticulate::use_virtualenv(venv, required=TRUE)  # venv binden
            reticulate::py_discover_config()
            reticulate::py_run_string("
              import sys, numpy, qmoms
              print('PY:', sys.executable)
              print('numpy:', numpy.__version__)
              print('qmoms: OK')
              ")
          } else {
            stop('reticulate not installed')
          }
          RS

      - name: Run tests (with Python parity enabled)
        run: |
          Rscript - <<'RS'
          Sys.setenv(RQMOMS_BUILD_PY="1", RQMOMS_VENV="python/.venv")
          Sys.unsetenv("RETICULATE_PYTHON")
          reticulate::use_virtualenv("python/.venv", required=TRUE)
          devtools::test()
          RS

      - name: Build vignettes and pkgdown (with comparison)
        run: |
          Rscript - <<'RS'
          Sys.setenv(RQMOMS_BUILD_PY="1", RQMOMS_VENV="python/.venv")
          Sys.unsetenv("RETICULATE_PYTHON")
          reticulate::use_virtualenv("python/.venv", required=TRUE)
          devtools::build_vignettes()
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
          RS

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
