name: parity

on:
  workflow_dispatch:
    inputs:
      qmoms_ref:
        description: "vilkovgr/qmoms git ref (branch/tag/SHA)"
        required: false
        default: "main"
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: write

jobs:
  parity:
    runs-on: ubuntu-latest

    env:
      RQMOMS_BUILD_PY: "1"
      RQMOMS_VENV: ${{ github.workspace }}/python/.venv
      QMOMS_REF: ${{ github.event.inputs.qmoms_ref || 'main' }}

    steps:
      - name: Checkout rqmoms
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies (incl. reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # ... (Header/checkout/Setup-R/Setup-Python/venv erstellen wie gehabt)

      - name: Create venv and install Python deps + vilkovgr/qmoms
        shell: bash
        run: |
          python -m venv python/.venv
          source python/.venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel build setuptools-scm
          python -m pip install numpy pandas scipy tqdm
          python -m pip install "git+https://github.com/vilkovgr/qmoms@${{ github.event.inputs.qmoms_ref || 'main' }}"
          # Sanity check: venv + imports
          python - <<'PY'
          import sys, numpy
          print("VENV python:", sys.executable)
          print("numpy:", numpy.__version__)
          try:
              import qmoms
              print("qmoms: OK")
          except Exception as e:
              print("qmoms import FAILED:", e)
              raise
          PY

      # --- WICHTIG: Interpreter IM R-PROZESS setzen (nicht nur via env) ---

      - name: Debug reticulate config
        run: |
          Rscript -e 'Sys.setenv(RQMOMS_VENV=normalizePath("python/.venv"), RETICULATE_PYTHON=normalizePath("python/.venv/bin/python")); cat(Sys.getenv(c("RQMOMS_BUILD_PY","RQMOMS_VENV","RETICULATE_PYTHON")), sep="\n"); if (requireNamespace("reticulate", quietly=TRUE)) { reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE); reticulate::py_discover_config() }'

      - name: Run tests (with Python parity enabled)
        run: |
          Rscript -e 'Sys.setenv(RETICULATE_PYTHON=normalizePath("python/.venv/bin/python"), RQMOMS_VENV=normalizePath("python/.venv"), RQMOMS_BUILD_PY="1"); devtools::test()'

      - name: Build vignettes and pkgdown (with comparison)
        run: |
          Rscript -e 'Sys.setenv(RETICULATE_PYTHON=normalizePath("python/.venv/bin/python"), RQMOMS_VENV=normalizePath("python/.venv"), RQMOMS_BUILD_PY="1"); devtools::build_vignettes(); pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
