name: pkgdown

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      # tell the vignette to actually run Python chunks
      RQMOMS_BUILD_PY: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up R (RSPM)
        uses: r-lib/actions/setup-r@v2
        with: { use-public-rspm: true }

      - name: Install R deps (pkgdown + reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install qmoms + numpy into the runner’s Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy pandas scipy tqdm "git+https://github.com/vilkovgr/qmoms@main"

      - name: Render article + build site in one session (Python bound)
        env:
          RQMOMS_BUILD_PY: "1"
          RETICULATE_PYTHON: ${{ env.pythonLocation }}/bin/python
        run: |
          Rscript -e 'stopifnot(requireNamespace("reticulate", quietly=TRUE));
                      reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE);
                      reticulate::py_discover_config();
                      # If needed, add NumPy 2.x shim here:
                      reticulate::py_run_string("import numpy as np; np.NAN = getattr(np, \"NAN\", np.nan)");
                      # Knit article (executes Python now)
                      rmarkdown::render("vignettes/python-parity.Rmd", output_dir="vignettes", clean=TRUE, envir=new.env());
                      # Build site in the same process (so reticulate stays bound)
                      pkgdown::build_site_github_pages(new_process=FALSE, install=FALSE)'


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
