name: pkgdown

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      # tell the vignette to actually run Python chunks
      RQMOMS_BUILD_PY: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up R (RSPM)
        uses: r-lib/actions/setup-r@v2
        with: { use-public-rspm: true }

      - name: Install R deps (pkgdown + reticulate)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::pkgdown
            any::rmarkdown
            any::reticulate
          needs: website

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install numpy + qmoms into this Python
        shell: bash
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          python -m pip install numpy pandas scipy tqdm
          python -m pip install "git+https://github.com/vilkovgr/qmoms@main"
          python - <<'PY'
          import sys, numpy, qmoms
          print("PY:", sys.executable)
          print("NumPy:", numpy.__version__)
          print("qmoms import: OK")
          PY

      # Important: run clean R sessions and pin reticulate to the toolcache python
      - name: Pre-render parity article and build site (same session, Python bound)
        env:
          RETICULATE_PYTHON: ${{ env.pythonLocation }}/bin/python
          R_ENVIRON_USER: /dev/null
          R_PROFILE_USER: /dev/null
          RQMOMS_BUILD_PY: "1"
        run: |
          Rscript --vanilla - <<'RS'
          stopifnot(requireNamespace("reticulate", quietly=TRUE))
          reticulate::use_python(Sys.getenv("RETICULATE_PYTHON"), required=TRUE)

          # 1) Pre-render the parity vignette (this writes vignettes/python-parity.html)
          rmarkdown::render(
            "vignettes/python-parity.Rmd",
            output_dir = "vignettes",
            clean      = TRUE,
            envir      = new.env()
          )

          # 2) Build the whole site in THIS session (no extra processes)
          pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
          RS

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
